name: brownie_cli
description: Bring tasty automation into your flutter project
version: 0.0.1
author: Appala Reddy
homepage: https://github.com/apple-ec/brownie_cli.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  io: ^1.0.2
  mason: ^0.0.1-dev.43
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^1.5.3

executables:
  brownie: brownie